[build]
builder = "DOCKERFILE"
dockerfilePath = "/railway/loki/Dockerfile"

[deploy]
startCommand = "loki -config.file=/etc/loki/config.yaml"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10