"""create_luthien_log_table

Revision ID: 50deccdf11ab
Revises: 93bd05330754_revised
Create Date: 2025-05-20 17:03:31.776398

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50deccdf11ab"
down_revision: Union[str, None] = "93bd05330754_revised"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "luthien_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("datatype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_luthien_log_datetime"), "luthien_log", ["datetime"], unique=False)
    op.create_index(op.f("ix_luthien_log_datatype"), "luthien_log", ["datatype"], unique=False)
    op.create_index(op.f("ix_luthien_log_id"), "luthien_log", ["id"], unique=False)
    op.create_index(op.f("ix_luthien_log_transaction_id"), "luthien_log", ["transaction_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_luthien_log_transaction_id"), table_name="luthien_log")
    op.drop_index(op.f("ix_luthien_log_id"), table_name="luthien_log")
    op.drop_index(op.f("ix_luthien_log_datatype"), table_name="luthien_log")
    op.drop_index(op.f("ix_luthien_log_datetime"), table_name="luthien_log")
    op.drop_table("luthien_log")
    # ### end Alembic commands ###
