"""Initial SQLModel tables

Revision ID: 6e27f83a84ac
Revises:
Create Date: 2025-04-17 17:06:16.623413

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e27f83a84ac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_value", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_api_keys_key_value"), "client_api_keys", ["key_value"], unique=True)
    op.create_index(op.f("ix_client_api_keys_name"), "client_api_keys", ["name"], unique=False)
    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("policy_class_path", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policies_name"), "policies", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policies_name"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_client_api_keys_name"), table_name="client_api_keys")
    op.drop_index(op.f("ix_client_api_keys_key_value"), table_name="client_api_keys")
    op.drop_table("client_api_keys")
    # ### end Alembic commands ###
