apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_INTERNAL_URL:-http://loki.railway.internal:3100}
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      maxLines: 1000